apiVersion: v1
kind: Service
metadata:
  name: {{ include "hydra.fullname" . }}-admin
  labels:
    {{- include "hydra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.adminport }}
      targetPort: 4445
      protocol: TCP
      name: adminport
  selector:
    {{- include "hydra.selectorLabels" . | nindent 4 }}
