apiVersion: v1
kind: Service
metadata:
  name: {{ include "hydra.fullname" . }}
  labels:
    {{- include "hydra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.publicport }}
      targetPort: 4444
      protocol: TCP
      name: publicport
  selector:
    {{- include "hydra.selectorLabels" . | nindent 4 }}
