apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hydra.fullname" . }}
  labels:
    {{- include "hydra.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hydra.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hydra.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hydra.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-mypostgres
        image: busybox
        command: ["sh", "-c", "until nslookup postgres.default.svc.cluster.local; do echo waiting for postgres; sleep 2; done"]
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: publicport
              containerPort: 4444
            - name: adminport
              containerPort: 4445
          env:
          - name: DSN
            value: "{{ .Values.env.dsn }}"
          - name: URLS_SELF_ISSUER
            value: "{{ .Values.env.selfIssuer }}"
          - name: URLS_CONSENT
            value: "{{ .Values.env.consent }}"
          - name: URLS_LOGIN
            value: "{{ .Values.env.login }}"
          - name: URLS_LOGOUT
            value: "{{ .Values.env.logout }}"
          - name: OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES
            value: "public,pairwise"
          - name: SERVE_COOKIES_SAME_SITE_MODE
            value: "Lax"
          - name: OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT
            value: youReallyNeedToChangeThis

          command: ['hydra']
          args: [
            'serve', 
            'all',
            {{- if .Values.dangerousForceHttp }}
            '--dangerous-force-http',
            {{- end}} 
            ]

          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: adminport
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: adminport
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
