apiVersion: batch/v1
kind: Job
metadata:
  name: create-client-job-1
spec:
  template:
    spec:
      initContainers:
        - name: init-mypostgres
          image: busybox
          command: ["sh", "-c", "until nslookup my-hydra-service.default.svc.cluster.local; do echo waiting for postgres; sleep 2; done"]
      containers:
        - name: create-client
          image: oryd/hydra:v1.7.4
          command: ["hydra", "clients", "create", "--endpoint", "http://my-hydra-service.default.svc.cluster.local:4445", "--id", "3gitea-client", "--secret", "secret", "--grant-types",  "authorization_code,refresh_token", "--response-types", "code,id_token", "--scope", "openid,offline", "--callbacks", "http://127.0.0.1:30000/user/oauth2/ORY_Hydra/callback"]
          #command: ["hydra", "token", "user", "--client-id", "gitea-client", "--client-secret", "secret", "--endpoint",  "http://my-hydra-service.default.svc.cluster.local:4444/", "--port", "5555", "--scope", "openid,offline"]
      restartPolicy: Never
  backoffLimit: 5
  
  #create 2 two jobs for two commands
  #change endpoint with service endpoint
  #my-gitea-service.default.svc.cluster.local
  #my-hydra-service.default.svc.cluster.local