apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hydra
spec:
  selector:
    matchLabels:
      run: my-hydra-pod
  replicas: 1
  template:
    metadata:
      labels:
        run: my-hydra-pod
    spec:
      initContainers:
      - name: init-mypostgres
        image: busybox
        command: ["sh", "-c", "until nslookup postgres.default.svc.cluster.local; do echo waiting for postgres; sleep 2; done"]

      containers:
      - name: my-hydra-container
        image: oryd/hydra:v1.7.4
        command: ['hydra']
        args: ['serve', 'all', '--dangerous-force-http']
        ports:
        - containerPort: 4444
          name: publicport
        - containerPort: 4445
          name: adminport
        env:
        - name: DSN
          value: "postgres://hydra:secret@postgres.default.svc.cluster.local:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4"
        - name: URLS_SELF_ISSUER
          value: "http://127.0.0.1:30044"
        - name: URLS_CONSENT
          value: "http://127.0.0.1:30001/consent"
        - name: URLS_LOGIN
          value: "http://127.0.0.1:30001/login"
        - name: URLS_LOGOUT
          value: "http://127.0.0.1:30001/logout"
        - name: OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES
          value: "public,pairwise"
        - name: SERVE_COOKIES_SAME_SITE_MODE
          value: "Lax"
        - name: OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT
          value: youReallyNeedToChangeThis
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: my-hydra-service
  labels:
    run: my-hydra-pod
spec:
  type: NodePort
  ports:
  - port: 4444
    protocol: TCP
    name: publicport
    targetPort: 4444
    nodePort: 30044
  - port: 4445
    protocol: TCP
    name: adminport
    targetPort: 4445
    nodePort: 30045
  selector:
    run: my-hydra-pod