# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: hydra

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go install github.com/gobuffalo/packr/v2/packr2
    - packr2

builds:
  -
    id: hydra
    flags:
      - -a
    ldflags:
      - -s -w -X github.com/ory/hydra/cmd.Version={{.Tag}} -X github.com/ory/hydra/cmd.Commit={{.FullCommit}} -X github.com/ory/hydra/cmd.Date={{.Date}}
    binary: hydra
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    goos:
      - freebsd
      - linux
      - windows
      - darwin

archives:
  - builds:
      - hydra
    id: hydra-archive
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
brews:
  - tap:
      owner: ory
      name: homebrew-hydra
    goarm: 6
    ids:
    - hydra-archive
    homepage:  https://www.ory.sh
    commit_author:
      name: aeneasr
      email: aeneas@ory.sh

scoop:
  bucket:
    owner: ory
    name: scoop-hydra
  homepage:  https://www.ory.sh
  commit_author:
    name: aeneasr
    email: aeneas@ory.sh

dockers:
  - dockerfile: Dockerfile
    binaries:
      - hydra
    image_templates:
      - "oryd/hydra:v{{ .Major }}"
      - "oryd/hydra:v{{ .Major }}.{{ .Minor }}"
      - "oryd/hydra:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "oryd/hydra:{{ .Tag }}"
      - "oryd/hydra:latest"
  - dockerfile: Dockerfile-alpine
    binaries:
      - hydra
    image_templates:
      - "oryd/hydra:v{{ .Major }}-alpine"
      - "oryd/hydra:v{{ .Major }}.{{ .Minor }}-alpine"
      - "oryd/hydra:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-alpine"
      - "oryd/hydra:{{ .Tag }}-alpine"
      - "oryd/hydra:latest-alpine"

release:
  prerelease: auto
