version: '3'

services:
  gitea:
    image: gitea/gitea:latest
    restart: always
    hostname: gitea.example.com
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - '8000:3000' # http
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

